export const Products = [
  {
    id: "1",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "2",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "3",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "4",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "5",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "6",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "7",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "8",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "9",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "10",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "11",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "12",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "13",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "14",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "15",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "16",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "17",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "18",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    specifications: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
];